CREATE DATABASE NextSoft;
GO
USE NextSoft;

CREATE TABLE Condominio (
	Id INT IDENTITY PRIMARY KEY,
	Nome VARCHAR(100) NOT NULL,
	Bairro VARCHAR(100) NOT NULL
);
GO
CREATE TABLE Familia (
	Id INT IDENTITY PRIMARY KEY,
	Nome VARCHAR(100) NOT NULL,
	Id_Condominio INT NOT NULL,
	Apto INT NOT NULL,
	CONSTRAINT FK_Familia_Condominio FOREIGN KEY (Id_Condominio) REFERENCES Condominio (Id)
);
GO
CREATE TABLE Morador (
	Id INT IDENTITY PRIMARY KEY,
	Id_Familia INT NOT NULL,
	Nome VARCHAR(100) NOT NULL,
	Idade INT NOT NULL,
	CONSTRAINT FK_Morador_Familia FOREIGN KEY (Id_Familia) REFERENCES Morador (Id)
);
